[package]
name = "basic-4dk-sample-integrated-with-rocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
dddk_core = { path = "../../project/core-rust" }
